name: feature_{{feature.snakeCase()}}
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  meta: any
  json_annotation: any

dev_dependencies:
  json_serializable: any
  build_runner: any
  test: any
